#ifndef INTERFACE_H
#define INTERFACE_H

const char HTML_BODY[] =
"<!DOCTYPE html><html lang='pt'><head><meta charset='UTF-8'><meta name='viewport' content='width=device-width, initial-scale=1.0'>"
"<title>Estação Meteorológica</title>"
"<style>"
"body { font-family: Arial, sans-serif; background: #f4f7f9; margin: 0; padding: 0; color: #333; }"
"h1, h2 { text-align: center; }"
".container { max-width: 400px; margin: auto; padding: 20px; background: #fff; box-shadow: 0 0 10px rgba(0,0,0,0.1); border-radius: 8px; margin-top: 30px; }"
"#valor { font-size: 2.5em; margin: 20px 0; color: #336699; }"
"canvas { display: block; margin: 0 auto 20px; border: 1px solid #ccc; background: #fff; }"
"form label { display: block; margin-bottom: 10px; font-weight: bold; }"
"input[type='number'] { width: 100%; padding: 8px; box-sizing: border-box; margin-top: 4px; }"
"button { padding: 10px 15px; margin-top: 15px; background: #336699; color: white; border: none; border-radius: 4px; cursor: pointer; width: 100%; }"
"button:hover { background: #285280; }"
".info { font-size: 0.9em; text-align: center; margin-top: 10px; color: #888; }"
"</style>"
"<script>"
"let historico = [], paginaAtual = null, camposPreenchidos = false;"
"function atualizar() {"
"  fetch('/estado').then(res => res.json()).then(data => {"
"    document.getElementById('nome').innerText = data.nome;"
"    document.getElementById('valor').innerText = data.valor.toFixed(2) + ' ' + (data.unidade || '');"
"    historico = data.historico; desenharGrafico();"
"    if (paginaAtual !== data.pagina || !camposPreenchidos) {"
"      document.getElementById('lim_min').value = data.lim_min;"
"      document.getElementById('lim_max').value = data.lim_max;"
"      document.getElementById('offset').value = data.offset;"
"      paginaAtual = data.pagina; camposPreenchidos = true;"
"    }"
"  });"
"}"
"function desenharGrafico() {"
"  let c = document.getElementById('grafico'), ctx = c.getContext('2d');"
"  ctx.clearRect(0, 0, c.width, c.height);"
"  if (historico.length < 2) return;"
"  let min = Math.min(...historico), max = Math.max(...historico);"
"  if (min == max) { min -= 1; max += 1; }"
"  let w = c.width, h = c.height, n = historico.length;"
"  ctx.beginPath();"
"  for (let i = 0; i < n; i++) {"
"    let x = i * (w / (n - 1));"
"    let y = h - (h * (historico[i] - min) / (max - min));"
"    i === 0 ? ctx.moveTo(x, y) : ctx.lineTo(x, y);"
"  }"
"  ctx.strokeStyle = '#336699'; ctx.lineWidth = 2; ctx.stroke();"
"}"
"function enviarConfig() {"
"  let lim_min = parseFloat(document.getElementById('lim_min').value);"
"  let lim_max = parseFloat(document.getElementById('lim_max').value);"
"  let offset = parseFloat(document.getElementById('offset').value);"
"  fetch('/config', {"
"    method: 'POST', headers: { 'Content-Type': 'application/json' },"
"    body: JSON.stringify({ pagina: paginaAtual, lim_min, lim_max, offset })"
"  }).then(() => { camposPreenchidos = false; setTimeout(atualizar, 300); });"
"  return false;"
"}"
"function mudarPagina() {"
"  fetch('/pagina', { method: 'POST' }).then(() => { setTimeout(atualizar, 300); });"
"}"
"setInterval(atualizar, 1000); window.onload = atualizar;"
"</script></head><body>"
"<h1>Estação Meteorológica</h1>"
"<div class='container'>"
"  <h2 id='nome'>--</h2>"
"  <div id='valor'>--</div>"
"  <canvas id='grafico' width='320' height='100'></canvas>"
"  <form onsubmit='return enviarConfig();'>"
"    <label>Limite Mínimo: <input id='lim_min' type='number' step='any'></label>"
"    <label>Limite Máximo: <input id='lim_max' type='number' step='any'></label>"
"    <label>Offset: <input id='offset' type='number' step='any'></label>"
"    <button type='submit'>Salvar</button>"
"  </form>"
"  <button onclick='mudarPagina();'>Mudar Página</button>"
"  <p class='info'>Pressione o botão A para alternar a leitura exibida</p>"
"</div>"
"</body></html>";

#endif
